import { headers } from 'next/headers';

type Locale = 'en' | 'zh';

const dictionaries = {
    en: {
        metaTitle: "Quantify Report",
        metaDesc: "AI-powered market analysis generated by Phantom X Quantify.",
        header: {
            analysis: "Analysis",
        },
        scores: {
            macro: "Macro Score",
            tech: "Tech Score",
        },
        stats: {
            views: "views",
            approval: "Approval",
        },
        strategy: {
            title: "Strategy Plan",
            entry: "Entry",
            target: "Target",
            stop: "Stop",
            rationale: "Rationale",
            invalidation: "Invalidation",
        },
        position: {
            title: "Position Strategy",
            entry: "Scaled Entry",
            exit: "Scaled Exit",
            cost: "Avg Cost",
            summary: "Execution Plan",
        },
        option: {
            title: "Option Play",
            strategy: "Strategy",
            expiration: "Expiration",
            contract: "Contract",
        },
        thesis: {
            core: "Core Theme",
            correlation: "Market Correlation",
            bull: "Bull Case",
            bear: "Bear Case",
            macro: "Macro Environment",
            tech: "Technical Analysis",
        },
        footer: {
            generatedBy: "AI Analysis Generated by Quantify",
            disclaimer: "Not financial advice. Trading involves risk. Past performance is not indicative of future results.",
        },
        banner: {
            title: "Quantify",
            subtitle: "AI Trading Assistant",
            button: "Open App",
        },
        verdict: {
            bullish: "Bullish",
            bearish: "Bearish",
            neutral: "Neutral",
        },
        common: {
            trader: "Trader",
        },
        reaction: {
            question: "Was this analysis helpful?",
            thanks: "Thanks for your feedback!",
        }
    },
    zh: {
        metaTitle: "Quantify 分析报告",
        metaDesc: "由 Phantom X Quantify 生成的 AI 市场分析报告。",
        header: {
            analysis: "分析报告",
        },
        scores: {
            macro: "宏观评分",
            tech: "技术评分",
        },
        stats: {
            views: "次浏览",
            approval: "好评",
        },
        strategy: {
            title: "交易策略",
            entry: "入场",
            target: "目标",
            stop: "止损",
            rationale: "逻辑分析",
            invalidation: "失效条件",
        },
        position: {
            title: "仓位策略",
            entry: "分批建仓",
            exit: "分批止盈",
            cost: "平均成本",
            summary: "执行计划",
        },
        positionLevel: {
            note: "说明"
        },
        option: {
            title: "期权策略",
            strategy: "策略类型",
            expiration: "到期日",
            contract: "合约",
        },
        thesis: {
            core: "核心主题",
            correlation: "市场相关性",
            bull: "看涨逻辑",
            bear: "看跌逻辑",
            macro: "宏观环境",
            tech: "技术面分析",
        },
        footer: {
            generatedBy: "分析由 Quantify AI 生成",
            disclaimer: "本报告非投资建议。交易有风险，过往表现不代表未来收益。",
        },
        banner: {
            title: "Quantify",
            subtitle: "AI 交易助手",
            button: "打开 App",
        },
        verdict: {
            bullish: "看涨",
            bearish: "看跌",
            neutral: "中性",
        },
        common: {
            trader: "交易员",
        },
        reaction: {
            question: "该分析对你有帮助吗？",
            thanks: "感谢你的反馈！",
        }
    }
};

export async function getDictionary() {
    const headersList = await headers();
    const acceptLanguage = headersList.get('accept-language') || 'en';

    // Simple check: if Chinese is preferred at all, switch to zh
    // A robust parser would parse q-factors, but this suffices for en vs zh
    const isChinese = acceptLanguage.toLowerCase().includes('zh');
    return isChinese ? dictionaries.zh : dictionaries.en;
}
